---
# file: main.yml
- hosts: localhost
  roles:
    - role: provision_instances

- name: Install docker
  hosts: gcp_instances
  pre_tasks: 
    - name: Wait for SSH to come up
      local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 90
        state: started
  
  roles:
    - role: ansible-role-docker-ce
  vars:
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine

