---
# file: main.yml
- hosts: localhost
  roles:
    - role: provision_instances

- name: Create an instance
  hosts: gcp_instances
  gather_facts: no
  tasks:
  - name: Wait for SSH to come up
    local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 10
      timeout: 90
      state: started

- name: Install docker
  hosts: gcp_instances
  roles:
    - role: ansible-role-docker-ce
  vars:
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine

