---
# tasks file for provision_instances

  - name: create disk for vm1
    gcp_compute_disk:
      name: ansible-test-gcp-disk1
      size_gb: 128
      source_image: 'projects/centos-cloud/global/images/family/centos-7'
      zone: europe-west1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk1
  
  - name: create disk for vm2
    gcp_compute_disk:
      name: ansible-test-gcp-disk2
      size_gb: 128
      source_image: 'projects/centos-cloud/global/images/family/centos-7'
      zone: europe-west1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk2

  - name: create address for vm1
    gcp_compute_address:
      name: ansible-test-gcp-ip1
      region: europe-west1
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      network_tier: PREMIUM
      state: present
    register: address1
    
  - name: create address for vm2
    gcp_compute_address:
      name: ansible-test-gcp-ip2
      region: europe-west1
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      network_tier: PREMIUM
      state: present
    register: address2

  - name: create instance 1
    gcp_compute_instance:
      name: "docker1"
      machine_type: n1-standard-2
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk1 }}"
      labels:
        environment: testing
        owner: matteo_faticanti
        os: centos
      network_interfaces:
      - network:
        access_configs:
        - name: External NAT
          nat_ip: "{{ address1 }}"
          type: ONE_TO_ONE_NAT
      metadata:
        items:
        - key: ssh-keys
          value: "gcpuser:{{ gcp_ssh_key }}"
      zone: europe-west1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: vm1
 
  - name: create instance 2
    gcp_compute_instance:
      name: "docker2"
      machine_type: n1-standard-2
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk2 }}"
      labels:
        environment: testing
        owner: matteo_faticanti
        os: centos
      network_interfaces:
      - network:
        access_configs:
        - name: External NAT
          nat_ip: "{{ address2 }}"
          type: ONE_TO_ONE_NAT
      metadata:
        items:
        - key: ssh-keys
          value: "gcpuser:{{ gcp_ssh_key }}"
      zone: europe-west1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: vm2
   
  - name: Add vm1 to groupname
    add_host:
      groupname=gcp_instances
      hostname={{ vm1.networkInterfaces[0].accessConfigs[0].natIP }}
  - name: Add vm2 to groupname
    add_host:
      groupname=gcp_instances
      hostname={{ vm2.networkInterfaces[0].accessConfigs[0].natIP }}
